export const groupsTypes = {
  SET_GROUP_DETAILS: "SET_GROUP_DETAILS",
  ADD_NEW_GROUP_DETAILS: "ADD_NEW_GROUP_DETAILS",
  ADD_ENTIRE_USER_SPECIFIC_GROUP_DETAILS:"ADD_ENTIRE_USER_SPECIFIC_GROUP_DETAILS",
  UPDATE_GROUP_INFO:"UPDATE_GROUP_INFO"
};
